baseURL = "http://example.org/"
languageCode = "en-us"
title = "Dylan's Portfolio"
[menu]
  [[menu.nav]]
    name = "Blog"
    url = "https://dev.to/dyllandry"
  [[menu.nav]]
    name = "GitHub"
    url = "https://github.com/dyllandry/"
  [[menu.nav]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/dylanglandry/"

